#################################
# DO NOT update this file manually, it is autogenerated
#################################

resource "aws_s3_bucket_lifecycle_configuration" "msk_topics_retention" {
  bucket = "uw-dev-pubsub-msk-data-keep-backup"

  rule {
    id     = "default-to-intelligent-tiering"
    status = "Enabled"
    filter {}
    transition {
      days          = 0
      storage_class = "INTELLIGENT_TIERING"
    }
  }

  rule {
    id     = "account-identity.account-management-events"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/account-identity.account-management-events/" }
  }

  rule {
    id     = "account-identity.address.lookup.analytics.v1"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/account-identity.address.lookup.analytics.v1/" }
  }

  rule {
    id     = "account-identity.dev.account.events.anonymized.v0"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/account-identity.dev.account.events.anonymized.v0/" }
  }

  rule {
    id     = "account-identity.from-prod.account.events.anonymized.v0"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/account-identity.from-prod.account.events.anonymized.v0/" }
  }

  rule {
    id     = "account-identity.legacy.account.eqdb.events"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/account-identity.legacy.account.eqdb.events/" }
  }

  rule {
    id     = "account-identity.to.anonymize"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/account-identity.to.anonymize/" }
  }

  rule {
    id     = "account-identity.verification.events.v1"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/account-identity.verification.events.v1/" }
  }

  rule {
    id     = "auth-customer.iam-credentials-v1-public"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/auth-customer.iam-credentials-v1-public/" }
  }

  rule {
    id     = "auth-customer.iam-credentials-v1"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/auth-customer.iam-credentials-v1/" }
  }

  rule {
    id     = "auth-customer.iam-dpd-v1"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/auth-customer.iam-dpd-v1/" }
  }

  rule {
    id     = "auth.iam-cerbos-audit-v1"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/auth.iam-cerbos-audit-v1/" }
  }

  rule {
    id     = "auth.iam-click-v2"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/auth.iam-click-v2/" }
  }

  rule {
    id     = "auth.iam-identitydb-v1"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/auth.iam-identitydb-v1/" }
  }

  rule {
    id     = "auth.iam-revoked-v1"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/auth.iam-revoked-v1/" }
  }

  rule {
    id     = "bex.internal.accountreadytobefulfilled_deadletter"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.accountreadytobefulfilled_deadletter/" }
  }

  rule {
    id     = "bex.internal.bill_fulfilled"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/bex.internal.bill_fulfilled/" }
  }

  rule {
    id     = "bex.internal.bill_regeneration"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.bill_regeneration/" }
  }

  rule {
    id     = "bex.internal.bill_regeneration_deadletter"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.bill_regeneration_deadletter/" }
  }

  rule {
    id     = "bex.internal.bill_regeneration_large_invoice"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/bex.internal.bill_regeneration_large_invoice/" }
  }

  rule {
    id     = "bex.internal.bill_regeneration_retry_1"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/bex.internal.bill_regeneration_retry_1/" }
  }

  rule {
    id     = "bex.internal.bill_regeneration_retry_2"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/bex.internal.bill_regeneration_retry_2/" }
  }

  rule {
    id     = "bex.internal.email_sender_deadletter"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.email_sender_deadletter/" }
  }

  rule {
    id     = "bex.internal.exstream_invoice_produced"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/bex.internal.exstream_invoice_produced/" }
  }

  rule {
    id     = "bex.internal.fulfilment_deadletter"
    status = "Enabled"
    expiration { days = 29 }
    filter { prefix = "kafka-backup/bex.internal.fulfilment_deadletter/" }
  }

  rule {
    id     = "bex.internal.fulfilment_large_invoice"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/bex.internal.fulfilment_large_invoice/" }
  }

  rule {
    id     = "bex.internal.fulfilment_retry_1"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/bex.internal.fulfilment_retry_1/" }
  }

  rule {
    id     = "bex.internal.fulfilment_retry_2"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/bex.internal.fulfilment_retry_2/" }
  }

  rule {
    id     = "bex.internal.invoice_ready_notifier_deadletter"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.invoice_ready_notifier_deadletter/" }
  }

  rule {
    id     = "bex.internal.mail_sender_deadletter"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.mail_sender_deadletter/" }
  }

  rule {
    id     = "bex.internal.mail_sender_reprint_deadletter"
    status = "Enabled"
    expiration { days = 15 }
    filter { prefix = "kafka-backup/bex.internal.mail_sender_reprint_deadletter/" }
  }

  rule {
    id     = "bex.public.fulfilment_events"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/bex.public.fulfilment_events/" }
  }

  rule {
    id     = "bex.transition.fulfilment_request"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/bex.transition.fulfilment_request/" }
  }

  rule {
    id     = "billing.DataStagedEventsFinance"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/billing.DataStagedEventsFinance/" }
  }

  rule {
    id     = "billing.bill-reconciliation-error-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/billing.bill-reconciliation-error-events/" }
  }

  rule {
    id     = "billing.billing-engine-events-bce-deadletter"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/billing.billing-engine-events-bce-deadletter/" }
  }

  rule {
    id     = "billing.fixed-width-file-processing-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/billing.fixed-width-file-processing-events/" }
  }

  rule {
    id     = "billing.historical-data-staged-events-finance"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/billing.historical-data-staged-events-finance/" }
  }

  rule {
    id     = "billing.transactions-auditor-diff.events"
    status = "Enabled"
    expiration { days = 61 }
    filter { prefix = "kafka-backup/billing.transactions-auditor-diff.events/" }
  }

  rule {
    id     = "billing.unified-bill-ready-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/billing.unified-bill-ready-events/" }
  }

  rule {
    id     = "cbc.DataProductEvents"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/cbc.DataProductEvents/" }
  }

  rule {
    id     = "contact-channels.article_feedback_v1"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.article_feedback_v1/" }
  }

  rule {
    id     = "contact-channels.dsar"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/contact-channels.dsar/" }
  }

  rule {
    id     = "contact-channels.dsar_conversation"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/contact-channels.dsar_conversation/" }
  }

  rule {
    id     = "contact-channels.dsar_job"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/contact-channels.dsar_job/" }
  }

  rule {
    id     = "contact-channels.finished_conversations"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/contact-channels.finished_conversations/" }
  }

  rule {
    id     = "contact-channels.finished_segments"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.finished_segments/" }
  }

  rule {
    id     = "contact-channels.finished_transcriptions"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/contact-channels.finished_transcriptions/" }
  }

  rule {
    id     = "contact-channels.genesys_eb_events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/contact-channels.genesys_eb_events/" }
  }

  rule {
    id     = "contact-channels.intents_v2"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.intents_v2/" }
  }

  rule {
    id     = "contact-channels.interactions_state_events"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/contact-channels.interactions_state_events/" }
  }

  rule {
    id     = "contact-channels.messenger_transcript_events"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.messenger_transcript_events/" }
  }

  rule {
    id     = "contact-channels.messenger_transcript_events_dlq"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.messenger_transcript_events_dlq/" }
  }

  rule {
    id     = "contact-channels.sent_agent_states"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/contact-channels.sent_agent_states/" }
  }

  rule {
    id     = "contact-channels.tracking_events"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.tracking_events/" }
  }

  rule {
    id     = "contact-channels.validated_intents_v2"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/contact-channels.validated_intents_v2/" }
  }

  rule {
    id     = "customer-support.account_history_eqdb_notifications_v1"
    status = "Enabled"
    expiration { days = 1 }
    filter { prefix = "kafka-backup/customer-support.account_history_eqdb_notifications_v1/" }
  }

  rule {
    id     = "customer-support.coffee_account_history_v1"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/customer-support.coffee_account_history_v1/" }
  }

  rule {
    id     = "customer-support.coffee_services"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/customer-support.coffee_services/" }
  }

  rule {
    id     = "customer-support.notes_v2"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/customer-support.notes_v2/" }
  }

  rule {
    id     = "customer-support.payments_audit_log_v1"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/customer-support.payments_audit_log_v1/" }
  }

  rule {
    id     = "customer-support.reminders_notifications_v1"
    status = "Enabled"
    expiration { days = 1 }
    filter { prefix = "kafka-backup/customer-support.reminders_notifications_v1/" }
  }

  rule {
    id     = "customer-support.reminders_v1"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/customer-support.reminders_v1/" }
  }

  rule {
    id     = "customer-support.ticketing_v2"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/customer-support.ticketing_v2/" }
  }

  rule {
    id     = "customer-support.vulnerability_v7"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/customer-support.vulnerability_v7/" }
  }

  rule {
    id     = "data-infra.bill-integration.bill-telemetry"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.bill-integration.bill-telemetry/" }
  }

  rule {
    id     = "data-infra.bill-integration.bill-to-kubernetes"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.bill-integration.bill-to-kubernetes/" }
  }

  rule {
    id     = "data-infra.bill-integration.kubernetes-to-bill-energy-meter-reading"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.bill-integration.kubernetes-to-bill-energy-meter-reading/" }
  }

  rule {
    id     = "data-infra.bill-integration.kubernetes-to-bill"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.bill-integration.kubernetes-to-bill/" }
  }

  rule {
    id     = "data-infra.bill_event_bridge.dlq"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.bill_event_bridge.dlq/" }
  }

  rule {
    id     = "data-infra.e2e.json"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.e2e.json/" }
  }

  rule {
    id     = "data-infra.e2e.multi-dpd"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.e2e.multi-dpd/" }
  }

  rule {
    id     = "data-infra.e2e.multi"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.e2e.multi/" }
  }

  rule {
    id     = "data-infra.e2e.multi_project"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.e2e.multi_project/" }
  }

  rule {
    id     = "data-infra.e2e.non-std-envelope"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.e2e.non-std-envelope/" }
  }

  rule {
    id     = "data-infra.e2e.proto"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.e2e.proto/" }
  }

  rule {
    id     = "data-infra.product.v1.events.dlq.alerts"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/data-infra.product.v1.events.dlq.alerts/" }
  }

  rule {
    id     = "data-infra.product.v1.events.dlq"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.product.v1.events.dlq/" }
  }

  rule {
    id     = "data-infra.product.v1.events.requeue"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/data-infra.product.v1.events.requeue/" }
  }

  rule {
    id     = "data-infra.uw.data-infra.pubsubbrige.snowplow"
    status = "Enabled"
    expiration { days = 6 }
    filter { prefix = "kafka-backup/data-infra.uw.data-infra.pubsubbrige.snowplow/" }
  }

  rule {
    id     = "data-infra.uw.data-infra.test.pla1275"
    status = "Enabled"
    expiration { days = 2 }
    filter { prefix = "kafka-backup/data-infra.uw.data-infra.test.pla1275/" }
  }

  rule {
    id     = "energy-billing.internal.billing-adapter-deadletter"
    status = "Enabled"
    expiration { days = 29 }
    filter { prefix = "kafka-backup/energy-billing.internal.billing-adapter-deadletter/" }
  }

  rule {
    id     = "energy-billing.internal.billing-adapter-retry-1"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/energy-billing.internal.billing-adapter-retry-1/" }
  }

  rule {
    id     = "energy-billing.internal.billing-adapter-retry-2"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/energy-billing.internal.billing-adapter-retry-2/" }
  }

  rule {
    id     = "energy-platform.eqdb-loader.service"
    status = "Enabled"
    expiration { days = 1 }
    filter { prefix = "kafka-backup/energy-platform.eqdb-loader.service/" }
  }

  rule {
    id     = "energy-platform.gentrack.billing.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/energy-platform.gentrack.billing.events/" }
  }

  rule {
    id     = "energy-platform.gentrack.market_interactions.events"
    status = "Enabled"
    expiration { days = 181 }
    filter { prefix = "kafka-backup/energy-platform.gentrack.market_interactions.events/" }
  }

  rule {
    id     = "energy-platform.gentrack.meter.read.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/energy-platform.gentrack.meter.read.events/" }
  }

  rule {
    id     = "energy-platform.gentrack.meterpoint.events"
    status = "Enabled"
    expiration { days = 181 }
    filter { prefix = "kafka-backup/energy-platform.gentrack.meterpoint.events/" }
  }

  rule {
    id     = "energy-platform.gentrack.migration.events"
    status = "Enabled"
    expiration { days = 181 }
    filter { prefix = "kafka-backup/energy-platform.gentrack.migration.events/" }
  }

  rule {
    id     = "energy-platform.meter.read.events.v3"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/energy-platform.meter.read.events.v3/" }
  }

  rule {
    id     = "energy-platform.property.migration.events"
    status = "Enabled"
    expiration { days = 181 }
    filter { prefix = "kafka-backup/energy-platform.property.migration.events/" }
  }

  rule {
    id     = "energy-platform.tariff.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/energy-platform.tariff.events/" }
  }

  rule {
    id     = "help-and-support.self_serve_submissions"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/help-and-support.self_serve_submissions/" }
  }

  rule {
    id     = "help-and-support.self_serve_submissions_dlq"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/help-and-support.self_serve_submissions_dlq/" }
  }

  rule {
    id     = "iam-audit.ingest-v1"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/iam-audit.ingest-v1/" }
  }

  rule {
    id     = "ledgers.account-balance.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/ledgers.account-balance.events/" }
  }

  rule {
    id     = "ledgers.account.migrated.events"
    status = "Enabled"
    expiration { days = 1 }
    filter { prefix = "kafka-backup/ledgers.account.migrated.events/" }
  }

  rule {
    id     = "ledgers.transaction.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/ledgers.transaction.events/" }
  }

  rule {
    id     = "payment-platform.card-deadletter.v1.internal.payment-methods"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.card-deadletter.v1.internal.payment-methods/" }
  }

  rule {
    id     = "payment-platform.card-deadletter.v1.internal"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.card-deadletter.v1.internal/" }
  }

  rule {
    id     = "payment-platform.card.v1.internal.notifications"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.card.v1.internal.notifications/" }
  }

  rule {
    id     = "payment-platform.card.v1.internal.payment-methods"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.card.v1.internal.payment-methods/" }
  }

  rule {
    id     = "payment-platform.card.v1.internal"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.card.v1.internal/" }
  }

  rule {
    id     = "payment-platform.notifications.stripe.raw"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.notifications.stripe.raw/" }
  }

  rule {
    id     = "payment-platform.notifications.tx"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.notifications.tx/" }
  }

  rule {
    id     = "payment-platform.notifications.worldpay.raw"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.notifications.worldpay.raw/" }
  }

  rule {
    id     = "payment-platform.openbanking-deadletter.v1.internal.payment-methods"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.openbanking-deadletter.v1.internal.payment-methods/" }
  }

  rule {
    id     = "payment-platform.openbanking-deadletter.v1.internal.payments"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.openbanking-deadletter.v1.internal.payments/" }
  }

  rule {
    id     = "payment-platform.openbanking-deadletter.v1.internal.settlements"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.openbanking-deadletter.v1.internal.settlements/" }
  }

  rule {
    id     = "payment-platform.openbanking.v1.internal.payment-methods"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.openbanking.v1.internal.payment-methods/" }
  }

  rule {
    id     = "payment-platform.openbanking.v1.internal.payments"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.openbanking.v1.internal.payments/" }
  }

  rule {
    id     = "payment-platform.openbanking.v1.internal.settlements"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.openbanking.v1.internal.settlements/" }
  }

  rule {
    id     = "payment-platform.payment-analysis.payment-method"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment-analysis.payment-method/" }
  }

  rule {
    id     = "payment-platform.payment-deadletter.v1.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment-deadletter.v1.events/" }
  }

  rule {
    id     = "payment-platform.payment-method-deadletter.v1.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment-method-deadletter.v1.events/" }
  }

  rule {
    id     = "payment-platform.payment-method.v1.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment-method.v1.events/" }
  }

  rule {
    id     = "payment-platform.payment-method.v1.public.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment-method.v1.public.events/" }
  }

  rule {
    id     = "payment-platform.payment.data-staged"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.data-staged/" }
  }

  rule {
    id     = "payment-platform.payment.enriched-txs"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.enriched-txs/" }
  }

  rule {
    id     = "payment-platform.payment.gateway.reconciliation.status-changed"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment.gateway.reconciliation.status-changed/" }
  }

  rule {
    id     = "payment-platform.payment.gateway.reconciliation"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment.gateway.reconciliation/" }
  }

  rule {
    id     = "payment-platform.payment.method-created"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment.method-created/" }
  }

  rule {
    id     = "payment-platform.payment.method-linked"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment.method-linked/" }
  }

  rule {
    id     = "payment-platform.payment.method-verified"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment.method-verified/" }
  }

  rule {
    id     = "payment-platform.payment.payment"
    status = "Enabled"
    expiration { days = 366 }
    filter { prefix = "kafka-backup/payment-platform.payment.payment/" }
  }

  rule {
    id     = "payment-platform.payment.v1.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.v1.events/" }
  }

  rule {
    id     = "payment-platform.payment.v1.public.events.cbc_topup_v3"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.v1.public.events.cbc_topup_v3/" }
  }

  rule {
    id     = "payment-platform.payment.v1.public.events.debt"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.v1.public.events.debt/" }
  }

  rule {
    id     = "payment-platform.payment.v1.public.events.debt_payment_plan"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.v1.public.events.debt_payment_plan/" }
  }

  rule {
    id     = "payment-platform.payment.v1.public.events.pp_test"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.v1.public.events.pp_test/" }
  }

  rule {
    id     = "payment-platform.payment.v1.public.events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/payment-platform.payment.v1.public.events/" }
  }

  rule {
    id     = "pubsub.examples"
    status = "Enabled"
    expiration { days = 1 }
    filter { prefix = "kafka-backup/pubsub.examples/" }
  }

  rule {
    id     = "pubsub.plan-topic-restore.large"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/pubsub.plan-topic-restore.large/" }
  }

  rule {
    id     = "pubsub.plan-topic-restore.normal"
    status = "Enabled"
    expiration { days = 4 }
    filter { prefix = "kafka-backup/pubsub.plan-topic-restore.normal/" }
  }

  rule {
    id     = "pubsub.proximo-example"
    status = "Enabled"
    expiration { days = 3 }
    filter { prefix = "kafka-backup/pubsub.proximo-example/" }
  }

  rule {
    id     = "pubsub.restore-test.billing.unified-bill-ready-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/pubsub.restore-test.billing.unified-bill-ready-events/" }
  }

  rule {
    id     = "staging-ept.DataStagedEventsFinance"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/staging-ept.DataStagedEventsFinance/" }
  }

  rule {
    id     = "staging-ept.bill-reconciliation-error-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/staging-ept.bill-reconciliation-error-events/" }
  }

  rule {
    id     = "staging-ept.billing-engine-events-bce-deadletter"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/staging-ept.billing-engine-events-bce-deadletter/" }
  }

  rule {
    id     = "staging-ept.fixed-width-file-processing-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/staging-ept.fixed-width-file-processing-events/" }
  }

  rule {
    id     = "staging-ept.historical-data-staged-events-finance"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/staging-ept.historical-data-staged-events-finance/" }
  }

  rule {
    id     = "staging-ept.transactions-auditor-diff.events"
    status = "Enabled"
    expiration { days = 61 }
    filter { prefix = "kafka-backup/staging-ept.transactions-auditor-diff.events/" }
  }

  rule {
    id     = "staging-ept.unified-bill-ready-events"
    status = "Enabled"
    expiration { days = 31 }
    filter { prefix = "kafka-backup/staging-ept.unified-bill-ready-events/" }
  }

  rule {
    id     = "unicom.bill-events"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.bill-events/" }
  }

  rule {
    id     = "unicom.bill-failed"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.bill-failed/" }
  }

  rule {
    id     = "unicom.bounce.2019.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.bounce.2019.1/" }
  }

  rule {
    id     = "unicom.braze_backfill"
    status = "Enabled"
    expiration { days = 181 }
    filter { prefix = "kafka-backup/unicom.braze_backfill/" }
  }

  rule {
    id     = "unicom.cancel-status.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.cancel-status.1/" }
  }

  rule {
    id     = "unicom.cancellation.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.cancellation.1/" }
  }

  rule {
    id     = "unicom.caps-consent"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.caps-consent/" }
  }

  rule {
    id     = "unicom.caps"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.caps/" }
  }

  rule {
    id     = "unicom.clx-report"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.clx-report/" }
  }

  rule {
    id     = "unicom.comms-api-requests"
    status = "Enabled"
    expiration { days = 181 }
    filter { prefix = "kafka-backup/unicom.comms-api-requests/" }
  }

  rule {
    id     = "unicom.comms-fallback.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.comms-fallback.1/" }
  }

  rule {
    id     = "unicom.cost-calculated.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.cost-calculated.1/" }
  }

  rule {
    id     = "unicom.email-batch.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-batch.1/" }
  }

  rule {
    id     = "unicom.email-post-delivery.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-post-delivery.1/" }
  }

  rule {
    id     = "unicom.email-released-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-critical.1/" }
  }

  rule {
    id     = "unicom.email-released-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-important.1/" }
  }

  rule {
    id     = "unicom.email-released-mock-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-mock-critical.1/" }
  }

  rule {
    id     = "unicom.email-released-mock-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-mock-important.1/" }
  }

  rule {
    id     = "unicom.email-released-mock.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-mock.1/" }
  }

  rule {
    id     = "unicom.email-released-ses-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-ses-critical.1/" }
  }

  rule {
    id     = "unicom.email-released-ses-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-ses-important.1/" }
  }

  rule {
    id     = "unicom.email-released-ses.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released-ses.1/" }
  }

  rule {
    id     = "unicom.email-released.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-released.1/" }
  }

  rule {
    id     = "unicom.email-status.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.email-status.1/" }
  }

  rule {
    id     = "unicom.failed"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.failed/" }
  }

  rule {
    id     = "unicom.go-inspire-letter-status.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.go-inspire-letter-status.1/" }
  }

  rule {
    id     = "unicom.letter-batch-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-batch-critical.1/" }
  }

  rule {
    id     = "unicom.letter-batch-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-batch-important.1/" }
  }

  rule {
    id     = "unicom.letter-batch.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-batch.1/" }
  }

  rule {
    id     = "unicom.letter-released-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-released-critical.1/" }
  }

  rule {
    id     = "unicom.letter-released-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-released-important.1/" }
  }

  rule {
    id     = "unicom.letter-released-mock-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-released-mock-critical.1/" }
  }

  rule {
    id     = "unicom.letter-released-mock-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-released-mock-important.1/" }
  }

  rule {
    id     = "unicom.letter-released-mock.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-released-mock.1/" }
  }

  rule {
    id     = "unicom.letter-released.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-released.1/" }
  }

  rule {
    id     = "unicom.letter-send-adare"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-send-adare/" }
  }

  rule {
    id     = "unicom.letter-status.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.letter-status.1/" }
  }

  rule {
    id     = "unicom.mparticle-output-integration"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.mparticle-output-integration/" }
  }

  rule {
    id     = "unicom.orchestration-entity.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.orchestration-entity.1/" }
  }

  rule {
    id     = "unicom.orchestration-rule-execution.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.orchestration-rule-execution.1/" }
  }

  rule {
    id     = "unicom.outbound-call-request"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.outbound-call-request/" }
  }

  rule {
    id     = "unicom.push-notification-released.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.push-notification-released.1/" }
  }

  rule {
    id     = "unicom.push-notification-status.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.push-notification-status.1/" }
  }

  rule {
    id     = "unicom.rejected"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.rejected/" }
  }

  rule {
    id     = "unicom.rendered.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.rendered.1/" }
  }

  rule {
    id     = "unicom.requests"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.requests/" }
  }

  rule {
    id     = "unicom.scheduled.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.scheduled.1/" }
  }

  rule {
    id     = "unicom.send-notification.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.send-notification.1/" }
  }

  rule {
    id     = "unicom.sftp-status"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.sftp-status/" }
  }

  rule {
    id     = "unicom.sms-batch.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.sms-batch.1/" }
  }

  rule {
    id     = "unicom.sms-released-critical.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.sms-released-critical.1/" }
  }

  rule {
    id     = "unicom.sms-released-important.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.sms-released-important.1/" }
  }

  rule {
    id     = "unicom.sms-released.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.sms-released.1/" }
  }

  rule {
    id     = "unicom.sms-status.1"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.sms-status.1/" }
  }

  rule {
    id     = "unicom.status-bill-email-connector"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/unicom.status-bill-email-connector/" }
  }

  rule {
    id     = "unicom.status-energy-smets1-notifier"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/unicom.status-energy-smets1-notifier/" }
  }

  rule {
    id     = "unicom.status-finance-email-delivery-engine"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/unicom.status-finance-email-delivery-engine/" }
  }

  rule {
    id     = "unicom.status-v2"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/unicom.status-v2/" }
  }

  rule {
    id     = "unicom.status"
    status = "Enabled"
    expiration { days = 8 }
    filter { prefix = "kafka-backup/unicom.status/" }
  }

  rule {
    id     = "unicom.tests"
    status = "Enabled"
    expiration { days = 92 }
    filter { prefix = "kafka-backup/unicom.tests/" }
  }

}
